---
- hosts: all
  remote_user: root
  tasks:

    #System Packages
    - apt: upgrade=dist update_cache=yes
    - apt: pkg={{item}} state=latest
      with_items:
        - supervisor
        - git
        - htop
        - build-essential
        - mongodb
        - nodejs
        - npm
        - mongodb

    #Services
    - service: name=mongodb state=started
    - template: src=supervisor.conf
                dest=/etc/supervisor/conf.d/podwithfriends.conf
      notify: restart supervisor
    - service: name=supervisor state=started
    - file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

    #Repo
    - file: path=/opt/podwithfriends state=directory owner=root group=root
    - git: repo=git@github.com:njl/podwithfriends.git
            dest=/opt/podwithfriends accept_hostkey=True force=True
      notify: restart podwithfriends
    - npm: path=/opt/podwithfriends state=present
    - synchronize: src=../secrets/ dest=/opt/podwithfriends/secrets/
    - template: src=hosts dest=/opt/podwithfriends/secrets/HOSTNAME
    #- supervisorctl: name=podwithfriends state=started

    #Map port
    - command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3000

  handlers:
    - name: restart podwithfriends
      supervisorctl: name=podwithfriends state=restarted
    - name: restart supervisor 
      service: name=supervisor state=restarted

